ALTER TABLE tasks DROP INDEX uc_tasks_taskId_runId;
ALTER TABLE tasks MODIFY COLUMN runId INT NULL;
ALTER TABLE tasks MODIFY COLUMN taskId VARCHAR(32) NULL;
ALTER TABLE tasks DROP INDEX ix_tasks_buildrequestId;
ALTER TABLE tasks MODIFY COLUMN buildrequestId INT NOT NULL PRIMARY KEY;
